openapi: 3.0.3
info:
  version: 1.0.0
  title: TeamMates questionnaires API
  contact:
    name: LongCorp
    email: LongCorp@gmail.com
  
paths:
  /questionnaires:
    get:
      description: Gets all questionnaires by pages
      
      parameters:
        - name: page
          in: query
          description: Number of page
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          description: Limit items on page
          schema:
            type: integer
            format: int32

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QuestionnaireOut'
                  
        "400":
          description: Invalid data passed
          content:
            text/plain:
              schema:
                type: string
                example: Invalid data has passed

  /questionnaire:
    post:
      description: Create new questionnaire
      
      requestBody:
      
        description: Questionnaire
        required: true
        
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/QuestionnaireIn'
            
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionnaireOut'
  

components:
  schemas:
  
    QuestionnaireOut:
      description: Object of questionnaire
      required:
        - header
        - id
        - game
        - description
        - author_id
      properties:
        name:
          type: string
          example: 'Wanna find teammate Dota 2'
        questionnaire_id:
          type: string
          format: uuid
        game:
          $ref: '#/components/schemas/Game'
        description:
          type: string
        image:
          description: Image URL
          type: string
          format: uri
        author_id:
          type: integer
    
    QuestionnaireIn:
      description: Object of questionnaire
      required:
        - header
        - game
        - text
        - author_id
      properties:
        header:
          type: string
          example: 'Wanna find teammate Dota 2'
        game:
          $ref: '#/components/schemas/Game'
        description:
          type: string
        author_id:
          type: integer
        image:
          type: string
          format: binary
    
    Game:
      type: string #enum object of games
      enum:
        - 'CS2'
        - 'Dota 2'
        - 'GTA 5'
        - 'Volorant'
